name: build

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - docker/Dockerfile.dev
          - docker/Dockerfile.test
          - docker/Dockerfile.prod
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -f ${{ matrix.dockerfile }} -t ctx-aware:${{ github.run_id }} .
